### ISSUE TITLE
Shure MXCW module missing commands

### ISSUE THREAD

**Issue by jamesmthetech** [bitfocus/companion-module-shure-mxcw#6]
Shure MXCW module is missing some commands. The ones I needed for my current event are the mute and unmute commands since we have some users who don't mute their mic after speaking and sometimes the newer folks are confused by unmuting the mics.
Shure MXCW Command string can be found here: https://pubs.shure.com/command-strings/MXCW/en-US

Missing Command for mic on and off.
< SET 1 MIC_STATUS ON >
< SET 1 MIC_STATUS OFF > 

_Originally posted https://github.com/bitfocus/companion-module-requests/issues/1085#issuecomment-1834636407_

**Comment by peternewman** [comment]
Hi @jamesmthetech

You'd be better off posting this in the module's issues itself next time, although I suspect someone will be along to move it for you soon if not:
https://github.com/bitfocus/companion-module-shure-mxcw/issues
